//! Raw bindings to realm-core's C API, generated by `bindgen` in `build.rs`.
//!
//! Everything here is machine-written and does not follow the workspace's conventions, so the
//! relevant lints are turned off for this module alone rather than repo-wide.

#![expect(
    non_upper_case_globals,
    non_camel_case_types,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::multiple_unsafe_ops_per_block,
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
    reason = "generated code does not follow our conventions"
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
