[package]
name = "cleaner-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for osu-lazer-cleaner"

[lints]
workspace = true

[[bin]]
name = "osu-lazer-cleaner-cli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
cleaner-core = { path = "../cleaner-core" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
